# Close the pull request to trigger a Cleanup workflow, which will tear down the environment 
# and release any associated resources. 
# Then, check the GitHub Actions logs to ensure the environment is being cleaned up properly.

name: Close PR Environment
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
# on:
#   pull_request:
#     branches: [features]
#     types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3 

    - name: Remove PR environment in ElasticBeanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      run: |
        aws configure set default.region us-east-1
        aws elasticbeanstalk delete-environment --environment-name my-node-app-pr-${{ github.event.pull_request.number }}
